#!/bin/bash
# dir=$1
# tag=$2
# branch=$3

#echo "---- patch-lttng $1, $2, $3"

srcdir=$(pwd)/out/src

pkg=$1-${2#"v"}
worktree=$srcdir/$1/worktree/$3

if [ -e patches/$pkg/patches ]; then
    echo -e "\nPatching $worktree, $pkg"

    git -C $worktree reset --hard $2 >/dev/null

    patches=$(grep -v "^#" patches/$pkg/patches)
    for patch in $patches; do
	echo -e " --- $patch"
	git -C $worktree am -q -3 $PWD/patches/$pkg/$patch
	if [ $? -ne 0 ]; then
	    git -C $worktree am --abort
	    echo "FAILED: git -C $1 am -q -3 $PWD/patches/$pkg/$patch"
	    exit 1
	fi
    done

    git -C $worktree tag -f v_${3} >/dev/null
else
    echo -e "\nNo patches for $worktree, $pkg"
fi
