FROM ubuntu:20.04
LABEL maintainer="anders.wallin@windriver.com"

WORKDIR /root

ENV TERM xterm
ENV DEBIAN_FRONTEND noninteractive

ADD .gitconfig /root/.gitconfig

# Preparing packages needed by lttng 
RUN apt-get update
RUN apt-get install -y apt-utils

# userspace-rcu
RUN apt-get install -y gcc autoconf automake libtool bash

# babeltrace
RUN apt-get install -y gcc autoconf automake libtool bison flex libc6 libglib2.0-dev python3-dev libdw-dev libelf-dev asciidoc doxygen python3-sphinx
RUN apt-get remove -y libbabeltrace1

# lttng-ust
RUN apt-get install -y gcc autoconf automake libtool pkg-config asciidoc xmlto perl libnuma-dev

# lttng-tools
RUN apt-get install -y autoconf automake libtool bison flex libpopt-dev libxml2-dev swig libpfm4-dev bash kmod

# rcs
RUN apt-get install -y make git groff tzdata bsdmainutils
#RUN apt-get install -y  python3-pip psmisc

ENTRYPOINT ["/bin/bash"]
