FROM ubuntu:18.04
LABEL maintainer="anders.wallin@windriver.com"

WORKDIR /root

ENV TERM xterm
ENV HOME /root
ENV DEBIAN_FRONTEND noninteractive

ADD .gitconfig /root/.gitconfig

# Preparing packages needed by lttng 
RUN apt-get update
RUN apt-get install -y apt-utils
RUN apt-get install -y git libpopt-dev uuid-dev libxml2-dev automake autoconf libtool flex \
	bison make libc6 libc6-dev libglib2.0-0 libglib2.0-dev libpopt-dev python-pip python-dev emacs tzdata tmux \
	libelf-dev libdw-dev tig gdb sshpass asciidoc xmlto groff man kmod libnuma-dev ncurses-bin psmisc
RUN apt-get remove -y libbabeltrace1

# Installing lttng repos
RUN git clone https://github.com/wallinux/lttng-test.git
RUN make -C lttng-test update
RUN groupadd tracing

RUN mkdir -p /root/.ssh
ADD ssh.config /root/.ssh/config

ENTRYPOINT ["/bin/bash"]

