#!/bin/sh
#set -x

#VERBOSE=-v

HOSTIP=localhost
TARGETIP=localhost
TARGETNAME=$(hostname)

TESTAPP=../bin/gen-ust-events
NO_OF_EVENTS=10
SESSION=livetest

############################
echo ----------------------
echo "  lttng version:       " $(lttng -V)
echo "  babeltrace version:  " $(babeltrace -h | head -1)
echo "  lttng-relayd version:" $(lttng-relayd --version)
echo ----------------------

# cleanup if $SESSION already exist
rm -f $SESSION.out
lttng destroy $SESSION 2> /dev/null
sleep 1
rm -rf $HOME/lttng-traces

if [ "$TIMEOUT" != "" ]; then
    echo LTTNG_NETWORK_SOCKET_TIMEOUT=$TIMEOUT
    export LTTNG_NETWORK_SOCKET_TIMEOUT=$TIMEOUT
fi

lttng-relayd $VERBOSE -L net://$TARGETIP:5344 &
lttng_relayd_pid=$!

lttng create $SESSION -U net://$HOSTIP --live 1000000
lttng enable-channel $SESSION-channel -u -s $SESSION
lttng enable-event -a -u -c $SESSION-channel -s $SESSION
lttng list $SESSION

babeltrace -i lttng-live net://$TARGETIP/host/$TARGETNAME/$SESSION > $SESSION.out &

lttng start $SESSION
$TESTAPP $NO_OF_EVENTS
sleep 3
lttng stop $SESSION
sleep 3
lttng destroy $SESSION

no_of_events=$(grep tptest $SESSION.out | wc -l)
if [ "$no_of_events" = "$NO_OF_EVENTS" ]; then
    echo -e "\nTEST PASSED\n"
else
    echo -e "\nTEST FAILED, got $no_of_events and expected $NO_OF_EVENTS\n"
fi

sleep 1
kill $lttng_relayd_pid
