#!/bin/bash
set +x

[ -z $TEE ] && TEE=tee
[ -z $APP ] && APP=./tracetest
[ -z $NO_OF_THREADS ] && NO_OF_THREADS=3
[ -z $LOOP ] && LOOP=1000
[ -z $LIVETIME ] && LIVETIME=1000000

# local target
SERVER_IP=localhost
TARGET_IP=localhost
TARGET_CMD=
if [ $# = 1 ] && [ $1 = "remote" ]; then
    # remote target
    TARGET_IP=135.15.35.94
    SERVER_IP=135.15.35.1
    USER=root
    TARGET_CMD="ssh $USER@$TARGET_IP"
fi 

SESSION=livetest
BT_INDEX=0
DATE=$(date +%H_%M_%S)

prepare_target () {
    if [ $TARGET_IP != localhost ]; then
	echo Copy $APP to $USER@$TARGET_IP
	scp $APP $USER@$TARGET_IP:
    fi
    $TARGET_CMD killall lttng-consumerd
    $TARGET_CMD killall lttng-sessiond
    $TARGET_CMD sleep 1
    $TARGET_CMD ps -ef | grep lttng-*
    rm *.log
    $TARGET_CMD lttng-sessiond -d --no-kernel
    TARGET_NAME=$(echo $($TARGET_CMD hostname))

    ulimit -c unlimited
}

target_start () {
    echo $1
    $TARGET_CMD lttng create $SESSION -U net://$SERVER_IP --live $LIVETIME
    $TARGET_CMD lttng enable-event -a -u
    $TARGET_CMD lttng start
}

target_stop () {
    $TARGET_CMD lttng stop
    $TARGET_CMD lttng destroy $SESSION
}


start_trace () {
    target_start $1
  
    echo STARTING BABELTRACE
    babeltrace -i lttng-live net://localhost/host/$TARGET_NAME/$SESSION > babeltrace.log &

    $TARGET_CMD ./tracetest $1 $NO_OF_THREADS

    sleep 3
    ps -ef | grep -e lttng -e babeltrace
    target_stop
    wc -l babeltrace.log
}


print_version () {
    echo -e "--------------------------------------------"
    echo LTTNG VERSIONS:
    $TARGET_CMD lttng -V
    babeltrace -h | head -1
    echo -e "--------------------------------------------\n"
}

############################
prepare_target
print_version

# start relay daemon
lttng-relayd -L net://localhost:5344 &> lttng-relayd.log &
lttng_relayd_pid=$!

echo -e "\nps ------------------------------------------"; ps -l

start_trace $LOOP

kill $lttng_relayd_pid

sleep 1
echo -e "\nps ------------------------------------------"; ps -l
