#!/bin/bash

source test.inc

start_trace () {
#    lttng-relayd -o $TRACEDIR &
#    sleep 1
    lttng create $1 -U net://$SERVER_IP --live $LIVETIME
    target_start $1
    PRINT_PS=1 ./tracetest $LOOP $NO_OF_THREADS
    sleep 1
    target_stop $1
    babeltrace $TRACEDIR | wc -l
}

############################
target_prepare
start_trace $SESSION
target_clean
