#!/bin/bash

source test.inc

start_trace () {
    lttng create $1 --snapshot -o $TRACEDIR
    target_start $1
    PRINT_PS=1 ./tracetest $LOOP $NO_OF_THREADS &
    sleep 1
    while [ ! -z $(pgrep tracetest) ]; do {
	sleep 5
	lttng snapshot -s $1 record
    } done

    target_stop $1
    babeltrace $TRACEDIR | wc -l
}

############################
target_prepare
start_trace $SESSION
target_clean
