#!/bin/bash

TESTS="snapshot"

for i in $TESTS; do
    fname=results/test-$i
    echo running $fname
    grep tracetest $fname.out | sed -e 's/  / /g' -e 's/^ //' | cut -d' ' -f 1 > $fname.csv
    gnuplot -p -e "set term pdf; set output '$fname.pdf'; plot '$fname.csv'" 
done
