#!/bin/bash
#set -x

[ -z $APP ] && APP=./tracetest
[ -z $NO_OF_THREADS ] && NO_OF_THREADS=3
[ -z $LOOPS ] && LOOPS=1000
[ -z $LIVETIME ] && LIVETIME=1000000

LIVESESSION=livetest
FILESESSION=filetest
TRACEDIR=$PWD/traces

HOSTNAME=$(hostname)

prepare () {
    rm -f *.out
    rm -rf $TRACEDIR
    killall -9 lttng-consumerd
    killall -9 lttng-sessiond
    killall -9 lttng-relayd
    lttng-sessiond -d --no-kernel
    sleep 1
}

print_version () {
    echo -e "--------------------------------------------"
    echo LTTNG VERSIONS:
    lttng -V
    babeltrace -h | head -1
    echo -e "--------------------------------------------\n"
}

start_livetrace () {
    lttng-relayd -b -L net://localhost:5344
    sleep 1
    lttng create $1 -U net://localhost --live $LIVETIME
    lttng enable-event -a -u
    lttng start $1
  
    babeltrace -i lttng-live net://localhost/host/$HOSTNAME/$1 > $1.out &

    $APP $LOOPS $NO_OF_THREADS

    sleep 5
    lttng stop $1
    lttng destroy $1
    killall -9 babeltrace
    killall -9 lttng-relayd

    wc -l $1.out
}


start_filetrace () {
    lttng-relayd -b -o $TRACEDIR
    sleep 1
    lttng create $1 -U net://localhost --live $LIVETIME
    lttng enable-event -a -u
    lttng start $1 
  
    $APP $LOOPS $NO_OF_THREADS

    sleep 5
    babeltrace $TRACEDIR > $1.out
    lttng stop $1
    lttng destroy $1
    killall -9 lttng-relayd

    wc -l $1.out
}

start_trace () {
    lttng-relayd -b -o $TRACEDIR -L net://localhost:5344
    sleep 1
    lttng create $1 -U net://localhost --live $LIVETIME
    lttng enable-event -a -u
    lttng start $1
   
    babeltrace -i lttng-live net://localhost/host/$HOSTNAME/$1 > $1.out &

    $APP $LOOPS $NO_OF_THREADS

    #sleep 1
    lttng stop $1
    babeltrace $TRACEDIR > $2.out
    #sleep 2
    lttng destroy $1
    sleep 2
    killall -9 babeltrace
    sleep 1
    killall -9 lttng-relayd

    wc -l $1.out
    wc -l $2.out
}



############################
prepare
print_version

start_trace $LIVESESSION $FILESESSION

#start_livetrace $LIVESESSION
#start_filetrace $FILESESSION

