#!/bin/bash
set +x

[ -z $TEE ] && TEE=tee
[ -z $APP ] && APP=./tracetest
[ -z $NO_OF_THREADS ] && NO_OF_THREADS=3
[ -z $LOOPS ] && LOOPS=3
#[ -z $DEBUG ] && DEBUG="-v -d"

# local target
SERVER_IP=localhost
TARGET_IP=localhost
TARGET_CMD=
if [ $# = 1 ] && [ $1 = "remote" ]; then
    # remote target
    TARGET_IP=135.15.35.94
    SERVER_IP=135.15.35.1
    USER=root
    TARGET_CMD="ssh $USER@$TARGET_IP"
fi 

SESSION=livetest
BT_INDEX=0
DATE=$(date +%H_%M_%S)
MINLOOP=1000
MAXLOOP=$(($MINLOOP+$LOOPS))

babeltrace_pid=-1

prepare_target () {
    if [ $TARGET_IP != localhost ]; then
	echo Copy $APP to $USER@$TARGET_IP
	scp $APP $USER@$TARGET_IP:
    fi
    TARGET_NAME=$(echo $($TARGET_CMD hostname))
    ulimit -c unlimited
}

target_start () {
    echo $1
    $TARGET_CMD lttng create $SESSION -U net://$SERVER_IP --live 1000000
    $TARGET_CMD lttng enable-event -a -u
    $TARGET_CMD lttng start
}

target_stop () {
    echo $1
    $TARGET_CMD lttng stop
    $TARGET_CMD lttng destroy $SESSION
}

target_restart () {
    echo $1
    target_stop $1
    target_start $1
}

start_trace () {
    echo $1
    target_start $1
  
    # start babeltrace if it's not running
    if [ "$(kill -0 $babeltrace_pid)" != "0" ]; then
	echo STARTING BABELTRACE
	babeltrace $DEBUG -i lttng-live net://localhost/host/$TARGET_NAME/$SESSION 2>&1 | $TEE babeltrace_$BT_INDEX.log &
	babeltrace_pid=$!
	BT_INDEX=$(($BT_INDEX+1))
    fi

    $TARGET_CMD ./tracetest $1 $NO_OF_THREADS
    sleep 2
    target_restart $1
    target_stop $1
#    sleep 1
}

target_start_stop () {
    echo $1
    $TARGET_CMD lttng create $SESSION -U net://$SERVER_IP --live 1000000
    $TARGET_CMD lttng enable-event -a -u

    #babeltrace -v -d -i lttng-live net://localhost/host/$TARGET_NAME/$SESSION &> babeltrace.log &
    babeltrace -v -d -i lttng-live net://localhost/host/$TARGET_NAME/$SESSION &
    babeltrace_pid=$!
    sleep 1

    #1
    $TARGET_CMD lttng start
    $TARGET_CMD ./tracetest $1 $NO_OF_THREADS
    sleep 1
    $TARGET_CMD lttng stop
    $TARGET_CMD lttng destroy $SESSION

    echo AAAAAAAAAAAAAAAAAAAAAAA
    ps -l | grep babeltrace

    #2
    $TARGET_CMD lttng create $SESSION -U net://$TARGET_IP --live 1000000
    $TARGET_CMD lttng enable-event -a -u
    $TARGET_CMD lttng start
    $TARGET_CMD ./tracetest $1 $NO_OF_THREADS
    sleep 1
    $TARGET_CMD lttng stop
    $TARGET_CMD lttng destroy $SESSION

    echo BBBBBBBBBBBBBBBBBBBBBBB
    ps -l | grep babeltrace

    sleep 1
    echo CCCCCCCCCCCCCCCCCCCCCCC
    ps -l | grep babeltrace


    #kill $babeltrace_pid
}


############################
prepare_target

echo ----------------------
echo LTTNG VERSIONS:
$TARGET_CMD lttng -V
babeltrace -h | head -1
echo ----------------------

# start relay daemon
lttng-relayd -v -L net://localhost:5344 &> lttng-relayd.log &
lttng_relayd_pid=$!
ps -l

for i in $(seq $MINLOOP $MAXLOOP); do
    start_trace $i
    if [ -e core ]; then
        echo core dumped!!
	tar czvf $0-$DATE.tgz core babeltrace*.log lttng-relayd.log
	ps -l
	break
    fi
done

kill $lttng_relayd_pid
sleep 1
ps -l
